### ISSUE TITLE
FlexibleJointState naming debate

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/roadmap#16]
We are in agreement that the "working name" of this message is not sufficient to be used upstream. Let's come up with an alternative that captures the essence of this message. 

The reasoning for the original name was that it is meant to be an alternative to `JointState.msg` but drops the hardcoded list of elements `position, velocity, effort` but allows to have a flexibly-defined list of interfaces and the values in them.

@jordan-palacios @Karsten1987 @artivis @destogl @piraka9011 @mateus-amarante

**Comment by gavanderhoorn** [comment]
Admittedly I haven't read all the discussion around this, but what is the main rationale for wanting to use a single message (type) / topic to carry the system/joint state?

An alternative could be to use dedicated datastreams for specific types of data. That would seem to remove the need for a flexible grab bag/union type message, as producers would publish an appropriate message for their type of data and consumers would subscribe to it (ie: controllers).

**Comment by mateus-amarante** [comment]
Suggestions: `generic_joint_state`, `universal_joint_state`, `composite_joint_state`, and `multi_interface_joint_state`.

**Comment by artivis** [comment]
Suggestions: `general`, `adjustable/adaptable/variable` or `interfaced` `_joint_state`

**Comment by bmagyar** [comment]
I started working with the `MultiInterfaceJointState`

**Comment by destogl** [comment]
@bmagyar sorry for not giving feedback.... I agree with your proposal! :)

**Comment by destogl** [comment]
@bmagyar: I believe we can close this for now, since there will probably be no sugestions anymore or they will be late.

**Comment by bmagyar** [comment]
Indeed, thanks

**Comment by Karsten1987** [comment]
what about `dynamic`?
