### ISSUE TITLE
`JointValues` msg type for `control_msgs`

### ISSUE THREAD

**Issue by ijnek** [ros-controls/roadmap#47]
Continuation of a meeting, that continued from [ROS Discourse: Msg type for publishing JointCommands](https://discourse.ros.org/t/msg-type-for-publishing-jointcommands/22451/14).

Reusing [control_msgs/DynamicJointState](https://github.com/ros-controls/control_msgs/blob/galactic-devel/control_msgs/msg/DynamicJointState.msg) covers the exact case that is being considered, but has a misleading name to be used for comanding joints.

Name candidates were:
* JointValues
* GenericJointValues
* VersatileJointValues

A concern was raised, that by using the same msg type for commanding and sensing the joints, users could misinterpret topics. Conversely, this allows piping the joint states directly into another robot's joint command, and could make some cool demos for _replicating_ movements. Both of these points seem valid.

However, I dont think there's a necessity for a new msg type just to prevent users from misinterpreting data. They should be focusing on the topic name, and not the msg type being sent.

My proposal would be to have a new msg type "JointValues.msg", with the same fields as 
 [control_msgs/DynamicJointState.msg](https://github.com/ros-controls/control_msgs/blob/galactic-devel/control_msgs/msg/DynamicJointState.msg), and deprecate the later in upcoming distros.

**Comment by gavanderhoorn** [comment]
> However, I dont think there's a necessity for a new msg type just to prevent users from misinterpreting data.

isn't this more about *machines* than humans?

Typing is mostly for machines to be able to assist humans and prevent them from making mistakes.

> They should be focusing on the topic name, and not the msg type being sent.

this seems like a strange thing to assert when talking about a typed pub-sub system.

If we take away the ability for a machine (ie: a compiler, or a MDE tool) to introspect a system and determine whether one node can communicate with another, we lose something valuable. There is certainly convenience in reusing message types, but it complicates interpreting the semantics of the data, which is actually really valuable when working in more complex systems.

> [..] using the same msg type for commanding and sensing the joints [..] allows piping the joint states directly into another robot's joint command, and could make some cool demos for replicating movements.

True, but this is also easily accomplished by inserting a simple node which performs the conversion.

While that may seem like an unnecessary thing to do (as you write, we could just use the same message type and directly connect things), at least it would make the intention completely clear (ie: we actually created a system which was intended to use the reported state of one system as the desired state of another) *and* it would remain machine checkable. The semantics of the whole system would make sense: something produces state, something converts that into desired state (or setpoints), and something consumes those setpoints.

There are already examples of messages with identical content but different type and thus different semantics. See [Accel](http://docs.ros.org/en/api/geometry_msgs/html/msg/Accel.html) and [Twist](http://docs.ros.org/en/api/geometry_msgs/html/msg/Twist.html) for instance.

**Comment by ijnek** [comment]
I'm not sure what the process is, if there are no other suggestions, am I free to go ahead and raise a PR for `control_msgs/msg/JointCommand.msg`?

**Comment by ijnek** [comment]
I'm going to close this as there doesn't seem much interest from other users, if others are interested, feel free to re-open.
