### ISSUE TITLE
About real-time safety of the controller manager

### ISSUE THREAD

**Issue by mhubii** [ros-controls/roadmap#64]
Dear maintainers,

I was brought here via a discussion on discourse (https://discourse.ros.org/t/comprehensive-survey-on-ros-2/40483/8?u=mhubii)

Strictly speaking, is the service mechanism in `ros2_control` real-time safe, e.g. for switching controllers? If not, what would need to be done to achieve this? Am I using `ros2_control` wrongly?

Feel free to close / re-direct. Thank you for your time!

**Comment by saikishor** [comment]
Hello @mhubii!

The ros2_control's controller_manager when used along with the `ros2_control_node` spawns another thread to execute the read, update and write methods. This thread will be configured with FIFO priority on a real-time enabled system. All the services of the controller_manager are run on a non-RT thread, it shouldn't affect any real-time performance in general.

I'll go ahead and close the issue for now. If you have more questions, feel free to open or write in the issue

**Comment by mhubii** [comment]
hi @saikishor, thank you very much for your response on discourse as well!
